---
- name: "Deploy {{ domain }} host config"
  template:
    src: host.conf.j2
    dest: "{{ nginx_root }}/conf.d/{{ domain }}.conf"
    owner: root
    group: root
    mode: '0644'
    backup: true
  notify: Reload nginx

- include_tasks: selinux.yml
  when: ansible_os_family == 'RedHat'

- name: "Enable {{ domain }} host"
  file:
    src: "{{ nginx_root }}/conf.d/{{ domain }}.conf"
    dest: "{{ nginx_root }}/conf.d-enabled/{{ domain }}.conf"
    state: link
    owner: root
    group: root
  notify: Reload nginx
