---
- name: Update apt cache
  apt:
    update_cache: true
  register: noobient_nginx_apt_updated
  when: (ansible_pkg_mgr == 'apt') and (noobient_nginx_apt_updated is not defined)

- include_tasks: wordpress.yml
  when: (noobient_nginx_wp_installed is not defined) and (mode == 'wordpress')

- include_tasks: php.yml
  when: (noobient_nginx_php_installed is not defined) and (mode == 'php' or mode == 'wordpress')

- include_tasks: nginx.yml
  when: noobient_nginx_installed is not defined

- include_tasks: config.yml
  when: noobient_nginx_configured is not defined

- include_tasks: host.yml
