---
- include_tasks: main2.yml
  vars:
    domain: "{{ item.domain }}"
    mode: "{{ item.mode }}"
    path: "{{ item.path | default('') }}"
    www_mode: "{{ item.www_mode | default('') }}"
    new_domain: "{{ item.new_domain | default('') }}"
    ssl_disabled: "{{ item.ssl_disabled | default('') }}"
    ssl_key: "{{ item.ssl_key | default('') }}"
    ssl_cert: "{{ item.ssl_cert | default('') }}"
    host_port: "{{ item.host_port | default('') }}"
    proxy_port: "{{ item.proxy_port | default('') }}"
  loop: "{{ nginx_batch }}"
  when: (nginx_batch is defined) and (nginx_batch.__class__.__name__ == 'list')

- include_tasks: main2.yml
  when: (nginx_batch is not defined) or (nginx_batch.__class__.__name__ != 'list')
