---
- name: Enable EPEL repo
  package:
    name: epel-release
    state: latest
  when: ansible_os_family == 'RedHat' and ansible_distribution != 'Fedora' and mode == 'moodle'

- name: Install packages common for WordPress / Moodle
  package:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - php-pdo
      - php-gd
      - php-opcache
      - php-mbstring
      - php-xml
      - "php{% if ansible_os_family == 'Debian' %}{{ noobient_nginx_php_ver }}{% endif %}-intl"
      - "php{% if ansible_os_family == 'RedHat' %}-pecl{% else %}{{ noobient_nginx_php_ver }}{% endif %}-zip"
  register: noobient_nginx_phpapps_installed

- name: Install packages for WordPress
  package:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - php-mysqlnd
      - php-json
  register: noobient_nginx_wp_installed
  when: mode == 'wordpress' and noobient_nginx_wp_installed is not defined

- name: Install packages for Moodle
  package:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - "php-dev{% if ansible_os_family == 'RedHat' %}el{% endif %}"
      - "libsodium{% if ansible_os_family == 'Debian' %}23{% endif %}"
      - "libsodium-dev{% if ansible_os_family == 'RedHat' %}el{% endif %}"
      - php-pgsql
      - php-soap
      - php-pear
  register: noobient_nginx_moodle_installed
  when: mode == 'moodle' and noobient_nginx_moodle_installed is not defined

- name: Install libsodium
  command:
    cmd: pecl install --nodeps libsodium
  register: noobient_nginx_sodium_install
  changed_when: noobient_nginx_sodium_installed_str not in noobient_nginx_sodium_install.stdout
  failed_when: noobient_nginx_sodium_install.rc != 0 and noobient_nginx_sodium_install.rc != 1
  when: mode == 'moodle' and noobient_nginx_sodium_install is not defined

# Apparently not available/working on EL8/EL9 rn
- name: Install ImageMagick PHP extension
  package:
    name: "php{% if ansible_os_family == 'RedHat' %}-pecl{% else %}{{ noobient_nginx_php_ver }}{% endif %}-imagick"
    state: latest
  when: ansible_distribution == 'Fedora' or ansible_os_family == 'Debian'

- name: Set PHP options for Moodle
  ini_file:
    path: "{{ noobient_nginx_php_ini }}"
    section: PHP
    option: "{{ noobient_nginx_php_moodle_opt.option }}"
    value: "{{ noobient_nginx_php_moodle_opt.value }}"
    mode: '0644'
    backup: true
  loop:
    - { option: 'max_input_vars', value: '5000' }
  loop_control:
    loop_var: noobient_nginx_php_moodle_opt
  notify: Reload PHP
  when: mode == 'moodle'

- name: Enable libsodium PHP module
  ini_file:
    path: /etc/php.d/99-libsodium.ini
    create: true
    section: ''
    option: extension
    value: sodium.so
    no_extra_spaces: true
    owner: root
    group: root
    mode: '0644'
  notify: Reload PHP
  when: mode == 'moodle'
