---
- name: Install PHP packages for WordPress
  package:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - php-pdo
      - php-gd
      - php-opcache
      - php-mysqlnd
      - php-json
      - php-mbstring
      - "php{% if ansible_pkg_mgr == 'apt' %}{{ noobient_nginx_php_ver }}{% endif %}-intl"
      - "php{% if ansible_pkg_mgr == 'dnf' %}-pecl{% else %}{{ noobient_nginx_php_ver }}{% endif %}-imagick"
      - "php{% if ansible_pkg_mgr == 'dnf' %}-pecl{% else %}{{ noobient_nginx_php_ver }}{% endif %}-zip"
  register: noobient_nginx_wp_installed
